Make Plugin easier to implement
codelicia/xulieta pull request #51
Opened 2020-11-13 17:01 UTC by EHER

With this Refactory will be possible to Compose Xulieta with new file format Parsers or Code Validator.

It breaks BC

2020-11-14 14:35 UTC, EHER commented on src/Parser/MarkdownParser.php
> +        return in_array($file->getExtension(), $this->supportedExtensions(), false);
This should be `return true`.

A markdown file is valid even if the extension is not supported.

2020-11-15 08:22 UTC, malukenho requested changes

2020-11-15 08:22 UTC, malukenho commented on src/Parser/MultipleParser.php
> +            if (! in_array($file->getExtension(), $parser->supportedExtensions())) {
It's missing the third argument.

2020-11-15 08:22 UTC, malukenho commented on src/Parser/MultipleParser.php
> +            if (in_array($file->getExtension(), $parser->supportedExtensions())) {
It's missing the third argument.

2020-11-15 08:22 UTC, malukenho commented on src/Parser/Parser.php
> +    /** @TODO find a better name */
Missing TODO

2020-11-15 08:22 UTC, malukenho commented
Apart from DCO, it is looking good 👍🏻

2020-11-16 18:27 UTC, malukenho approved these changes

2020-11-16 18:27 UTC, merged